---
# tasks file for welink.development

- import_tasks: samba.yml
  tags:
    - samba

- fail:
    msg: "GIT configuration not set. Please set 'git_config_name' and 'git_config_email' in your playbook variables."
  when: not git_config_name or not git_config_email

- name: Configure GIT
  template:
    src=gitconfig.j2
    dest="/home/vagrant/.gitconfig"
    owner=vagrant
    group=vagrant
    mode=0664
  when: git_config_name or git_config_email
