---
# tasks file for welink.development @samba

- name: Install SAMBA
  apt:
    name=samba
    state=present

- name: Configure SAMBA
  copy:
    src=smb.conf
    dest=/etc/samba/smb.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart samba

- name: Check if SAMBA user is already created
  shell: "pdbedit -L | grep {{ samba_user }}"
  ignore_errors: yes
  register: pdb

- name: Generate script for adding SAMBA user
  template:
    src=add_samba_user.j2
    dest="/tmp/add_samba_user.sh"
    mode=775
  when: pdb.rc != 0

- name: Generate SAMBA user
  shell: /tmp/add_samba_user.sh
  when: pdb.rc != 0

- name: Remove SAMBA user generating script
  file:
    path: /tmp/add_samba_user.sh
    state: absent
