---
# tasks file for welink.development @samba

- name: Install SAMBA
  apt:
    name=samba
    state=present

- name: Ensuse Samba shared folder exists
  file:
    path: "{{ samba_shared_folder }}"
    state: directory
    owner: "{{ samba_shared_folder_owner }}"
    group: "{{ samba_shared_folder_owner }}"
    mode: 0775

- name: Configure Samba
  template:
    src=smb.conf.j2
    dest="/etc/samba/smb.conf"
    owner=root
    group=root
    mode=0664
  when: samba_shared_folder and samba_shared_folder_owner
  notify:
    - restart samba
