---
# tasks file for welink.development @ssh_keys

- name: Check private key availability
  stat: path="{{ ssh_keys_private_key_path }}"
  register: private_key_status

- name: Check public key availability
  stat: path="{{ ssh_keys_public_key_path }}"
  register: public_key_status

- name: Copy ssh private key to VM if available
  copy:
    src: "{{ ssh_keys_private_key_path }}"
    dest: "/home/{{ ssh_keys_user }}/.ssh/"
    owner: "{{ ssh_keys_user }}"
    group: "{{ ssh_keys_user}}"
    mode: 0600
  when: private_key_status.stat.exists == True

- name: Authorize public key and provide easy SSH access
  authorized_key:
    user: "{{ ssh_keys_user }}"
    state: present
    key: "{{ lookup('file', ssh_keys_public_key_path) }}"
  when: public_key_status.stat.exists == True